### ISSUE TITLE
1.18.2 Mixin Error

### ISSUE THREAD

**Issue by kinhirozane** [DragonsPlusMinecraft/CreeperFirework-Forge#1]
forge 1.18.2 - 40.1.69

日志
[latest.log](https://pastebin.ubuntu.com/p/4yVW4Tb4Qt/)

**Comment by MarbleGateKeeper** [comment]
Pretty strange, it works well on my debugging environments, my local test server and teacon server. Any other mod installed?

**Comment by kinhirozane** [comment]
yay, this is the curse modpack of all installed mods at the time of the error. [DemoModPack](https://github.com/karlepus/karlepus/blob/master/FG1-0.0.1.zip)

**Comment by MarbleGateKeeper** [comment]
> yay, this is the curse modpack of all installed mods at the time of the error. [DemoModPack](https://github.com/karlepus/karlepus/blob/master/FG1-0.0.1.zip)

The result is kinda frustrating. I'll checked from 40.1.63 to 40.1.73, from Zulu Java to Oracle Java. None of that reproduced same error. I've received an issue of same error happening in curseforge page. so it must be something went wrong.
I bumped forge version to latest and just uploaded it to cuseforge. Would you mind give it a try?

**Comment by MarbleGateKeeper** [comment]
According to report from other user, this problem is solved.
